name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: name=default

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build -t mmurcia57/grafana-app .
          docker tag mmurcia57/grafana-app mmurcia57/grafana-app:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push mmurcia57/grafana-app:latest

      - name: Deploy to AWS ECS
        run: |
          # Configura AWS CLI aquí
          ecs-cli compose --project-name grafana-app service up
