name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker buildx create --use
          docker buildx build --push -t mmurcia57/grafana-app:latest -f terraform/Dockerfile terraform

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan  || (echo "Error during apply, executing terraform destroy" && terraform destroy -auto-approve && exit 1)
        working-directory: ./terraform  # Añadir esta línea para especificar el directorio de trabajo

      - name: Deploy to AWS ECS
        run: |
          # Puedes agregar comandos adicionales para configurar o validar tu despliegue en ECS
          echo "Despliegue en AWS ECS completado"
